version: "3.9"

x-common-variables: &common-variables
  JAMBONES_MYSQL_HOST: mysql
  JAMBONES_MYSQL_USER: jambones
  JAMBONES_MYSQL_PASSWORD: jambones
  JAMBONES_MYSQL_DATABASE: jambones
  JWT_SECRET: "5a3e38b5-3188-4936-89c9-fb0df3138b5c"
  ENCRYPTION_SECRET: "5a3e38b5-3188-4936-89c9-fb0df3138b5c"
  AUTHENTICATION_KEY: "5a3e38b5-3188-4936-89c9-fb0df3138b5c"
  NODE_ENV: production
  JAMBONES_TIME_SERIES_HOST: influxdb
  ENABLE_METRICS: 0
  JAMBONES_CLUSTER_ID: jb
  JAMBONES_REDIS_HOST: redis
  JAMBONES_REDIS_PORT: 6379
  JAMBONES_LOGLEVEL: info
  DRACHTIO_PORT: 9022
  DRACHTIO_SECRET: cymru

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080

  mysql:
    build: ./mysql
    volumes:
      - ./data_volume:/var/lib/mysql
    ports:
      - "3360:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "jambones"
      MYSQL_USER: "jambones"
      MYSQL_PASSWORD: "jambones"
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "--protocol", "tcp"]
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    ports:
      - "16379:6379"

  api-server:
    image: jambonz/api-server:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      <<: *common-variables
      HTTP_PORT: 3000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ""
    depends_on:
      - mysql
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
networks:
  default:
    driver: bridge
